### ISSUE TITLE
Doesn't work on 0.77 and up

### ISSUE THREAD

**Issue by ualex73** [OmenWild/home-assistant-z-wave-graph#10]
This script doesn’t work anymore on HA 0.77 and up … I get the following error:

`
/usr/local/bin/python3 /config/bin/z-wave-graph.py Traceback (most recent call last): File "/config/bin/z-wave-graph.py", line 36, in <module> import homeassistant.remote as remote ModuleNotFoundError: No module named 'homeassistant.remote'
`

**Comment by OmenWild** [comment]
Good to know, thanks for reporting. I'm still on 0.75.1, but I'll upgrade soonish and figure out what changed.

**Comment by kylerw** [comment]
I'm seeing the same behavior. I am in Docker but it was working previously.

**Comment by OmenWild** [comment]
New version up that uses the REST API as required by 0.77+. Please test and let me know if it works for you.

**Comment by walthowd** [comment]
@OmenWild Getting this when running:

```
[iMac:~/.homeassistant] hass$ /usr/local/bin/python3 /Users/hass/.homeassistant/scripts/z-wave-graph.py --config /Users/hass/.homeassistant/configuration.yaml --debug
Traceback (most recent call last):
  File "/Users/hass/.homeassistant/scripts/z-wave-graph.py", line 327, in <module>
    zwave = ZWave(config, args)
  File "/Users/hass/.homeassistant/scripts/z-wave-graph.py", line 183, in __init__
    if self.haconf['api'] is not None and 'api_password' in self.haconf['api']:
KeyError: 'api'
```

My configuration http section:

```
http:  
  api_password: !secret http_password
  base_url: 'my.domain.com:443'
  ssl_certificate: /etc/letsencrypt/live/my.domain.com/fullchain.pem
  ssl_key: /etc/letsencrypt/live/my.domain.com/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 10
  trusted_networks: 192.168.1.0/24
```

Using Python 3.6.4, and Home Assistant 0.77.3

**Comment by OmenWild** [comment]
I see why that exception happened, and it's an easy fix. I'm poking around the http: and api: sections to see what is actually required. trusted_networks seems to bypass the checks, so I'm trying to make sure it works without that.

**Comment by OmenWild** [comment]
I mis-read the docs, the api: section is not necessary, so I'll pull the password from the http: section, if it exists. I'm also checking for HASSIO_TOKEN, in preparation for making an addon. 

I pushed a new version, please try this one.

**Comment by walthowd** [comment]
Pulled latest, getting a few traces, this is the last:

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/Users/hass/.homeassistant/scripts/z-wave-graph.py", line 332, in <module>
    zwave = ZWave(config, args)
  File "/Users/hass/.homeassistant/scripts/z-wave-graph.py", line 191, in __init__
    m = self.request('/')
  File "/Users/hass/.homeassistant/scripts/z-wave-graph.py", line 208, in request
    response = get(url, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

Full traces here: https://hastebin.com/ituyolovel.sql

Is [localhost:8123 supposed to be hardcodes on line 204 of z-wave-graph.py](https://github.com/OmenWild/home-assistant-z-wave-graph/blob/89375df6d4bbb96c92273da67b2d5c6606d2eec2/bin/z-wave-graph.py#L204)?

**Comment by OmenWild** [comment]
>  Is localhost:8123 supposed to be hardcoded on line 204 of z-wave-graph.py?

Argh, definitely not. Nice catch, fixed and pushed. Please re-test.

**Comment by walthowd** [comment]
@OmenWild It verks!

https://www.dropbox.com/s/hhgpu2khgpwr9cj/Screenshot%202018-09-18%2014.04.05.png?dl=0

Thank you!

**Comment by OmenWild** [comment]
Awesome, thanks for working with me to get it debugged, and thanks for letting me know.
