### ISSUE TITLE
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

### ISSUE THREAD

**Issue by dabeeeenster** [OmenWild/home-assistant-z-wave-graph#4]
When trying to run the python command I get the following error:

```
(homeassistant) raspberrypi% python3 ./bin/z-wave-graph.py
Error fetching states
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/remote.py", line 206, in get_states
    item in req.json()]
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
```

**Comment by OmenWild** [comment]
There was one person on the Home Assistant forums that had the same issue which was fixed with the proper use of the `--ssl` flag. You might try that if you need a SSL connection to HA.

I just pushed a version that will dump the JSON when you call it with the `--debug` flag. If the `--ssl` flag does not fix the issue dump that output and I can look through it.

**Comment by dabeeeenster** [comment]
OK I get this:

`Error fetching states
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/remote.py", line 206, in get_states
    item in req.json()]
  File "/srv/homeassistant/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
{'nodes': [], 'edges': []}`

**Comment by dabeeeenster** [comment]
Hmm I actually think my zwave network is *really* confused. I just tried to run this https://github.com/magma1447/HomeAssistant-Zwave-ConnectionMap and am seeing nodes that the visualisation is showing as disconnected from my controller, but I can still control them. V odd! So seems like this is something of an edge case?

**Comment by dabeeeenster** [comment]
Hmm actually - I think it was the password that I was not specifying - I just edited the python to hard code my HA password and it looks like its now working?

**Comment by OmenWild** [comment]
Is your `base_url` unset or localhost by any chance? And do you require an API password?
EDIT: Ah, I see from your response you do require an API password. I made the assumption that anyone using localhost would not require a API password. I will update the script.

**Comment by OmenWild** [comment]
I uploaded a tweaked version that does not assume localhost means no API password. Please test and let me know if it fixes the issue for you.

**Comment by dabeeeenster** [comment]
Thats perfect - thanks

**Comment by OmenWild** [comment]
Sweet, thanks for letting me know.
